server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/second_hand?useSSL=false
    username: root
    password: GUyiwei_)*@@
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: smtp.qq.com
    port: 587
    username: 3089308393@qq.com
    password: zgzfzzzeethodfgb
    default-encoding: utf-8
    protocol: smtp
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true


mybatis:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名和下划线的自动转换

SavePath:
  ProfilePhoto: 'D:/Project/SecondHandHub/profile_photo/upload_photo/' # 图标的物理存储路径，确保以斜杠结尾
  ProfilePhotoMapper: '/profile-photo/'     # 图标映射路径，确保以斜杠结尾

